# Generated by Django 5.1.4 on 2025-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_address_patient_age_patient_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
