# Generated by Django 5.1.4 on 2025-01-23 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=datetime.date(2025, 1, 23), null=True),
        ),
    ]
