# Generated by Django 5.1.4 on 2025-01-25 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=datetime.date(2025, 1, 25), null=True),
        ),
    ]
