# Generated by Django 5.1.4 on 2025-01-26 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_mobile_alter_patient_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
